# Conventional Commit Configuration

types:
  - docs: Documentation only changes, usually affecting index, readme, gemspec, and/or _config
  - style: Changes that do not affect the meaning of the code
  - fix: A bug fix
  - chore: Other changes that don't modify src files
  - revert: Reverts a previous commit

scopes:
  all:
    - core
    - project
  docs:
    - project
  chore:
    - github
    - kommit

options:
  allowCustomScopes: true
  allowEmptyScopes: true
  remindToStageChanges: true
  allowBreakingChanges:
    - fix
  allowIssues:
    - feat
    - fix
    - docs