# Conventional Commit Configuration

types:
  - docs: Documentation only changes, usually affecting index, readme, gemspec, and/or _config
  - layout: Changes that affect the layouts
  - include: Changes that affect the includes
  - fix: A bug fix
  - chore: Other changes that don't modify src files
  - revert: Reverts a previous commit

scopes:
  all:
    - core
    - project
  layout:
    - default
  include:
    - head
  docs:
    - project
  chore:
    - github
    - kommit

options:
  allowCustomScopes: true
  allowEmptyScopes: true
  remindToStageChanges: true
  allowBreakingChanges:
    - fix
  allowIssues:
    - feat
    - fix
    - docs