# Conventional Commit Configuration

types:
  - ui: Changes that affect the components and overall layout of the theme
  - style: Changes that affect styling, mostly in SCSS
  - docs: Documentation only changes, usually affecting index, readme, gemspec, and/or _config
  - fix: Bug fixes, usually affecting the theme's functionality
  - chore: Other changes that don't modify src files
  - revert: Reverts a previous commit

scopes:
  all:
    - core
    - project
  ui:
    - default
    - head
  style:
    - sass
    - assets
  docs:
    - project
  chore:
    - github
    - kommit

options:
  allowCustomScopes: true
  allowEmptyScopes: true
  remindToStageChanges: true